---
notifications:
  email:
    on_success: never
    on_failure: change

language: python
python:
  - '2.7'
  - '3.6'

install:
  - pip install coveralls
  - python setup.py install

script:
  - python setup.py test

after_script:
  - coveralls
